---
- name: Create mealie config directory
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: /var/opt/mealie
    state: directory
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: mealie
    image: ghcr.io/mealie-recipes/mealie:{{ mealie_version }}
    state: quadlet
    quadlet_filename: mealie-container
    network: slirp4netns
    memory: 400m
    env:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      BASE_URL: https://{{ domain_name }}
      OPENAI_API_KEY: "{{ mealie_openai_key }}"
      API_DOCS: "false"
      OPENAI_SEND_DATABASE_DATA: "false"
      SMTP_HOST: "{{ mealie_smtp_host }}"
      SMTP_PORT: "{{ mealie_smtp_port }}"
      SMTP_FROM_NAME: Mealie
      SMTP_AUTH_STRATEGY: TLS
      SMTP_FROM_EMAIL: mealie@{{ domain_name }}
      SMTP_USER: mealie@{{ domain_name }}
      SMTP_PASSWORD: "{{ mealie_smtp_password }}"
    ports:
      - 9000:9000
    volumes:
      - /var/opt/mealie:/app/data:rw
    quadlet_options:
      - AutoUpdate=registry
      - Pull=always
      - |
        [Unit]
        After=network-online.target nss-lookup.target
        [Install]
        WantedBy=default.target
  notify:
    - Reload systemd for mealie
    - Restart mealie
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
