---
- name: Create caddy config directory
  become: true
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: /etc/caddy
    state: directory
- name: Generate Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    group: root
    mode: "0644"
    owner: root
  notify: Restart caddy
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: caddy
    image: ghcr.io/caddybuilds/caddy-cloudflare:{{ caddy_version }}
    state: quadlet
    quadlet_filename: caddy-container
    user: 1000:1000
    network: host
    volumes:
      - /etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /var/opt/caddy/config:/config:rw
      - /var/opt/caddy/data:/data:rw
    quadlet_options:
      - AutoUpdate=registry
      - Pull=always
      - |
        [Unit]
        After=network-online.target nss-lookup.target
        [Install]
        WantedBy=default.target
  notify:
    - Reload systemd for caddy
    - Restart caddy
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
